Esdt-Safe update + cleanup
multiversx/mx-sovereign-sc pull request #141
Opened 2024-10-10 10:10 UTC by andreiblt1304

2024-10-10 11:23 UTC, andreiblt1304 commented on esdt-safe/src/from_sovereign/transfer_tokens.rs
> -                        <Self as TransferTokensModule>::callbacks(self)
this will be reverted

2024-10-10 14:19 UTC, axenteoctavian requested changes

2024-10-10 14:19 UTC, axenteoctavian commented on esdt-safe/src/to_sovereign/create_tx.rs
> +
You can delete this empty line
```suggestion
```

2024-10-10 14:19 UTC, axenteoctavian commented on esdt-safe/src/to_sovereign/create_tx.rs
> +
You can delete this empty line
```suggestion
```

2024-10-10 14:19 UTC, axenteoctavian commented on esdt-safe/src/to_sovereign/create_tx.rs
```suggestion
```

2024-10-10 14:19 UTC, axenteoctavian commented on esdt-safe/src/from_sovereign/transfer_tokens.rs
> +    fn distribute_payments_callback(
From what I remember this function name is actually the Identifier for the events in the function and we explicitly want `execute` the identifier. Please revert this change.
```suggestion
    fn execute(
```

2024-10-11 08:34 UTC, axenteoctavian approved these changes

2024-10-11 09:33 UTC, merged