Cf coverage
multiversx/mx-sovereign-sc pull request #166
Opened 2024-11-05 09:57 UTC by andreiblt1304

2024-11-06 12:32 UTC, alyn509 approved these changes

2024-11-07 08:54 UTC, axenteoctavian requested changes

2024-11-07 08:54 UTC, axenteoctavian commented on chain-factory/src/factory.rs
> +    fn add_contracts_to_map(
This map is not used anywhere. I see you are using a storage for each template contract, not this `contract_mapper`.

2024-11-07 08:54 UTC, axenteoctavian commented on chain-factory/tests/chain_factory_tests.rs
> +    fn new(
This is `chain-factory` contract. Why on `new` you are deploying `chain-config` contract?

2024-11-07 08:54 UTC, axenteoctavian commented on chain-factory/src/factory.rs
I see a lot of problems with this chain-factory contract implementation, like:
- after `deploy_sovereign_chain_config_contract` you can't even know what's the chain_id to use for deploying other contracts
- is not ok to make the caller an `admin`
- the "admin" can deploy contracts with whatever chain_id he wants
- and more...

A simpler way is to have a mapper with `key = caller` and value = (chain_id string, contracts ContractMapArgs).
So, when you deploy chain_config you create entry in mapper for caller, then for the rest of contracts you check mapper exists for caller and add the new contract address. This way you don't need `chain_id` in deploy function and everything is a lot simpler.

2024-11-07 08:54 UTC, axenteoctavian commented on chain-factory/src/factory.rs
Just some notes for later updates:
- deploy contracts should be with proxy, not raw arguments
- factory contract should have a function that returns `true` if everything is ready for a chain to start, this needs to be used in esdt-safe to "complete setup phase"
- later, this contract should contain a new .rs file with a full deploy and setup phase and deposit+execute transactions

2024-11-07 09:17 UTC, axenteoctavian commented on chain-factory/src/factory.rs
Other optimizations:
If you force user deploy in a custom order then you can add addresses in `init` to complete some mappers and you won't need extra transactions in setup phase
1. chain-config 
2. header-verifier
3. fee-market
4. enshrine-esdt-safe

- this order can also be optimized to deploy more contracts in the same transaction, like (1, 2-3, 4) or (1-2, 3-4) or other
- at step 4 you can also do:
1. add header-verifier and `fee-market` addresses on `init` in enshrine
2. add `enshrine` address in `header-verifier`
3. add whitelist for `enshrine` in `token-handler` 
this way we get rid of 4 extra transactions in setup phase

2024-11-13 15:22 UTC, axenteoctavian commented on chain-factory/src/factory.rs
>          opt_sov_token_prefix: Option<ManagedBuffer>,
these should not be optional for main chain deploy
```suggestion
        wegld_identifier: TokenIdentifier,
        sov_token_prefix: ManagedBuffer,
```

2024-11-13 15:22 UTC, axenteoctavian commented on chain-factory/src/factory.rs
>      #[payable("EGLD")]
no need
```suggestion
```

2024-11-13 15:28 UTC, axenteoctavian approved these changes

2024-11-13 15:37 UTC, merged