Sovereign-Forge SC
multiversx/mx-sovereign-sc pull request #185
Opened 2024-11-19 13:53 UTC by andreiblt1304

Created the Sovereign-Forge SC that will call the Chain-Factory SC. Basically this contract will be the user's interaction with the Sovereign Chain in order to deploy and setup the needed modules and SCs. This PR contains the following:

- The newly generated Sovereign-Forge along side it's common modules: Utils and Storage
- The Phases module will call the endpoints from the Chain-Factory SC and deploy the needed contracts in `phases`

2024-11-19 15:02 UTC, axenteoctavian requested changes

2024-11-19 15:02 UTC, axenteoctavian commented on sovereign-forge/src/lib.rs
TODO for different PR
- define a "complete setup phase" for this contract where we check token-handlers and chain-factory storages are set
- only if the setup is completed, `deploy_phase_one` can be called

2024-11-19 15:02 UTC, axenteoctavian commented on sovereign-forge/src/phases.rs
> +
require `chain_factory_address` is not empty

2024-11-19 15:05 UTC, axenteoctavian requested changes

2024-11-19 15:05 UTC, axenteoctavian commented on sovereign-forge/src/lib.rs
> +    #[endpoint(registerTokenHandler)]
Only owner can call this endpoint

2024-11-19 15:05 UTC, axenteoctavian commented on sovereign-forge/src/lib.rs
> +    #[endpoint(registerChainFactory)]
Only owner can call this endpoint

2024-11-20 08:07 UTC, axenteoctavian commented on sovereign-forge/src/phases.rs
> +            chain_id
Should be like this. I don't know if shard id of type u32 can be printed there
```suggestion
            "There is no Chain-Factory address registered in shard {}",
            caller_shard_id
```

2024-11-20 08:52 UTC, axenteoctavian approved these changes

2024-11-20 10:16 UTC, mihaicalinluca approved these changes

2024-11-20 10:17 UTC, merged