Phase two
multiversx/mx-sovereign-sc pull request #197
Opened 2024-12-02 06:23 UTC by andreiblt1304

2024-12-02 15:28 UTC, axenteoctavian requested changes

2024-12-02 15:28 UTC, axenteoctavian commented on sovereign-forge/src/common/utils.rs
> +    fn get_sovereign_chain_id(&self, sovereign_creator: &ManagedAddress) -> ChainId<Self::Api> {
This function probably is not needed

2024-12-02 19:54 UTC, andreiblt1304 commented on sovereign-forge/src/phases.rs
> +        self.check_if_contract_deployed(&caller, ScArray::ChainConfig);
i thought we decided that we check the phase by checking the already deployed contracts inside that sovereign chain

2024-12-02 19:57 UTC, andreiblt1304 commented on sovereign-forge/tests/sovereign_forge_unit_tests.rs
The problem having too many contracts used inside just one unit test file, i think that the whole scenario with all the contracts should be tested inside an interactor. 
I only created unit tests for the internal logic of the contract, it's better to separate the unit and system testing.

2024-12-03 14:44 UTC, axenteoctavian approved these changes

2024-12-04 08:09 UTC, mihaicalinluca approved these changes

2024-12-04 08:13 UTC, merged